In [ ]:
# star patterns using while 

# *
# * *
# * * *
# * * * *
# * * * * *

In [ ]:
n = int(input("Enter the number of rows :"))
i = 0 
while i<n:
  print(i*"* ")
  i = i + 1

Enter the number of rows :6

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
import time 
n = int(input("Enter the number of rows :"))
i = 0 
while i<n:
  print(i*"* ")
  time.sleep(1)  #adds a delay of 1 second after every iteration
  i = i + 1

Enter the number of rows :5

* 
* * 
* * * 
* * * * 


In [ ]:
n = 0
i = 5 
while i>n:
  print(i*"* ")
  i = i - 1

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
# for loop 
# for(initialization;condition;increment/decrement) - c language
# for i in range(start,stop,step):

In [ ]:
for i in range(11):     #(start=0,stop=11,step=1) by default start is 0 and step is 1
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(-11,0,2):        # -5 -4 -3 -2 -1 0 1 2 3 4 5 6 7 8 9 10 11   (0,-5)
  print(i)

-11
-9
-7
-5
-3
-1


In [ ]:
for i in range(4,11):
  print(i)

4
5
6
7
8
9
10


In [ ]:
for i in range(0,11,2):                    # 0 - inclusive    11 - exclusive
  print(i)

0
2
4
6
8
10


In [ ]:
i = 0 
while i <= 10:
  print(i)
  i = i + 2

0
2
4
6
8
10


In [ ]:
for i in range(20,-1,-2):
  print(i)

20
18
16
14
12
10
8
6
4
2
0


In [ ]:
#iterations through sequences 
for i in "hello world":
  print(i)

h
e
l
l
o
 
w
o
r
l
d


In [ ]:
for i in ["aa",'bb','cc','dd']:
  print(i)

aa
bb
cc
dd


In [ ]:
for i in ("aa",'bb','cc','dd'):
  print(i)

aa
bb
cc
dd


In [ ]:
for i in {"aa",'bb','cc','dd'}:
  print(i)

bb
aa
cc
dd


In [ ]:
#iterate over the dictionary keys
for i in {1:'aa',2:'bb',3:'cc',4:'dd'}:
  print(i)

1
2
3
4


In [ ]:
#iterate over the dictionary values
data = {1:'aa',2:'bb',3:'cc',4:'dd'}

for i in data.values():
  print(i)

aa
bb
cc
dd


In [ ]:
#iterate over the dictionary items
data = {1:'aa',2:'bb',3:'cc',4:'dd'}

for i in data.items():
  print(i)

(1, 'aa')
(2, 'bb')
(3, 'cc')
(4, 'dd')


In [ ]:
# tables using a for loop 
n = int(input("Enter a number : "))
for i in range(1,11,1):
  print(f"{n} x {i} = {n*i}")

Enter a number : 3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


In [ ]:
for i in range(4):       #  (0,4,1)  = 0,1,2,3         
  for j in range(4):     #  (0,4,1)  = 0,1,2,3
    print(f"({i},{j})")    

(0,0)
(0,1)
(0,2)
(0,3)
(1,0)
(1,1)
(1,2)
(1,3)
(2,0)
(2,1)
(2,2)
(2,3)
(3,0)
(3,1)
(3,2)
(3,3)


In [ ]:
for i in range(5):       #  (0,5,1)  = 0,1,2,3,4        
  for j in range(3):     #  (0,3,1)  = 0,1,2
    print(f"({i},{j})")    

(0,0)
(0,1)
(0,2)
(1,0)
(1,1)
(1,2)
(2,0)
(2,1)
(2,2)
(3,0)
(3,1)
(3,2)
(4,0)
(4,1)
(4,2)


In [ ]:
import random   
# random is a library which generated psuedo random numbers 
random.randint(0,9)          # here 0 - inclusive   9 - inclusive (only for random library)

3

In [ ]:
print(random.randint(0,9),random.randint(0,9),random.randint(0,9))

0 7 5


In [ ]:
from random import randint
print(randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9))

6 6 7 9 6 7


In [ ]:
# time library 
import time 
seconds = time.time()
local_time = time.ctime(seconds)
print("Local time :",local_time)

Local time : Sun Apr 17 08:38:23 2022


In [ ]:
from datetime import datetime 
import pytz 

IST = pytz.timezone('Asia/Kolkata')

print("Current Time :",datetime.now(IST))

Current Time : 2022-04-17 14:23:53.371838+05:30


In [ ]:
# In built Functions     print(),len(),input(),sum(),min(),max()
# user defined functions - we write our own code inside this 

In [ ]:
def my_function():    #function definition 
  print("Hello World!")

In [ ]:
my_function()   #function call 
my_function()

Hello World!
Hello World!


In [ ]:
my_function()

Hello World!


In [ ]:
#use input for text in a function 
def user1():
  text = input("Enter the text :")
  print("Your entered text is :",text)

In [ ]:
user1()

Enter the text :abc123
Your entered text is : abc123


In [ ]:
def eve_odd():
  a = int(input("Enter a number :"))
  if a%2==0:
    print(f"{a} is Even")
  else:
    print(f"{a} is Odd")

In [ ]:
eve_odd()

Enter a number :3
3 is Odd


In [ ]:
def add(x,y):
  sum = x+y
  return sum 

add(2,3)

5

In [ ]:
def add_sub(x,y):
  sum = x+y
  difference = x-y 
  return sum,difference

add_sub(7,4)

(11, 3)

In [ ]:
def add_sub(x,y):
  print("Sum = ",x+y)
  print("Difference = ",x-y)

add_sub(7,4)

Sum =  11
Difference =  3


In [ ]:
# libraries in python (random,time,datetime,math,pytz,turtle)

# numpy
# matplotlib                     (extra - seaborn)
# pandas

In [ ]:
# NumPy - Numerical Python
!pip install numpy 

In [ ]:
import numpy as np  

In [ ]:
arr = np.array(22) #scalar
arr

array(22)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim  #prints the number of dimensions of the array 

0

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.ndim

1

In [ ]:
print(arr1)

[1 2 3 4 5]


In [ ]:
# 2 dimensional array 
arr2 = np.array([[1,2,3,4,5]])
arr2.ndim

2

In [ ]:
arr2

array([[1, 2, 3, 4, 5]])

In [ ]:
arr21 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr21

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
arr21.ndim

2

In [ ]:
arr21.shape

(2, 5)

In [ ]:
arr22 = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,5,7,3,2]])
arr22 

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 5, 7, 3, 2]])

In [ ]:
arr22.shape

(3, 5)

In [ ]:
# 3 dimensional array 
arr3 = np.array([[[1,2,3,4,5]]])
arr3.ndim

3

In [ ]:
arr31 = np.array([[[1,2,3,4,5],[6,7,8,9,0],[1,5,7,3,2]]])
arr31 

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [1, 5, 7, 3, 2]]])

In [ ]:
arr31.ndim

3

In [ ]:
#higher dimensions 
arr_n = np.array([1,2,3,4,5],ndmin = 7)
arr_n

array([[[[[[[1, 2, 3, 4, 5]]]]]]])

In [ ]:
a = np.array([1,2,3,4,5]) #1 dimensional arrays are the most commonly used arrays
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
a.shape  #(rows,columns)

(5,)

In [ ]:
a.size  #total number of values 

5

In [ ]:
a.dtype   #datatype of the elements in the numpy array 

dtype('int64')