In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a.ndim

1

In [ ]:
np.max(a)

5

In [ ]:
np.min(a)

1

In [ ]:
np.mean(a)

3.0

In [ ]:
b = np.array([4,2,3,6,7])
b

array([4, 2, 3, 6, 7])

In [ ]:
a+b  #a+b in lists was concatenation , a+b in numpy is addition

array([ 5,  4,  6, 10, 12])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 4, 2, 3, 6, 7])

In [ ]:
a-b

array([-3,  0,  0, -2, -2])

In [ ]:
a*b

array([ 4,  4,  9, 24, 35])

In [ ]:
a/b

array([0.25      , 1.        , 1.        , 0.66666667, 0.71428571])

In [ ]:
a%b

array([1, 0, 0, 4, 5])

In [ ]:
a//b

array([0, 1, 1, 0, 0])

In [ ]:
a[0]

1

In [ ]:
a
# # 1, 2, 3, 4, 5
#   0  1  2  3  4  - indexing
#  -5 -4  -3 -2 -1 - -ve indexing


array([1, 2, 3, 4, 5])

In [ ]:
a[0:4]    #0 - inclusive     4 - exclusive

array([1, 2, 3, 4])

In [ ]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
np.power(a,2)

array([ 1,  4,  9, 16, 25])

In [ ]:
np.power(a,3)

array([  1,   8,  27,  64, 125])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [ ]:
x = np.array([[1,2,3,4,5],[6,4,3,7,2]])
x

array([[1, 2, 3, 4, 5],
       [6, 4, 3, 7, 2]])

In [ ]:
x.ndim

2

In [ ]:
x[0][3]

4

In [ ]:
x[0,1] #locating a number inside a matrix using indexing

2

In [ ]:
x[1,3]

7

In [ ]:
x[1]

array([6, 4, 3, 7, 2])

In [ ]:
np.unique(a) #unique elements from numpy array a

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(0,20,2)    #arange(start, stop[, step])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [ ]:
np.linspace(0,15,3)

# Return evenly spaced numbers over a specified interval.

# Returns num evenly spaced samples, calculated over the
# interval [start, stop].

array([ 0. ,  7.5, 15. ])

In [ ]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b

array([4, 2, 3, 6, 7])

In [ ]:
np.sort(b) #ascending order sort

array([2, 3, 4, 6, 7])

In [ ]:
np.sort(b)[::-1] #desending order sort

array([7, 6, 4, 3, 2])

In [ ]:
b

array([4, 2, 3, 6, 7])

In [ ]:
np.argmin(b)  # index of smallest element

1

In [ ]:
np.argmax(b)  # index of largest element

4

In [ ]:
c = np.array(['aaa','bb','cc','dd','eeee'])
c

array(['aaa', 'bb', 'cc', 'dd', 'eeee'], dtype='<U4')

In [ ]:
c.dtype   #unicode character string (4 characters)

dtype('<U4')

In [ ]:
d = np.array([1,3.45,True,"aaa"])
d                                     #default is U32 characters

array(['1', '3.45', 'True', 'aaa'], dtype='<U32')

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones([15,15],dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
np.zeros(20,dtype=int)    #if we mention int by defaultit will consider as int64 (holds 64 bits data)
# np.zeros(20,dtype='int64')
# np.zeros(20,dtype='int32')
# np.zeros(20,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int16)

In [ ]:
#random library in numpy
np.random.randint(1,10,7) #gives 7 digits random numbers #ex-OTP number

array([8, 7, 4, 2, 4, 9, 7])

In [ ]:
np.random.randint(1,100,30)

array([70, 40, 82, 20, 32, 61,  9, 31, 45, 58, 37, 63, 18, 84, 91, 17, 81,
       70, 39, 81, 12, 41, 86, 94, 23, 40, 27, 75, 47, 11])

In [ ]:
# 31, 70, 94, 93,  6, 55, 95, 58, 92, 81, 43, 97, 54, 86, 30, 13, 73,
#        17, 32, 16, 91, 70, 99, 46, 74, 76, 32, 90, 22, 79]

# array([54, 79, 81,  8, 36, 72, 64, 66, 25, 17, 19, 30, 23, 20, 37, 75, 16,
#        45, 52,  5, 50, 46, 69, 19,  2, 83, 11,  8, 54,  9])

# array([70, 40, 82, 20, 32, 61,  9, 31, 45, 58, 37, 63, 18, 84, 91, 17, 81,
#        70, 39, 81, 12, 41, 86, 94, 23, 40, 27, 75, 47, 11])

In [ ]:
np.random.seed(565)  #initialized the random values to some particular fixed values
np.random.randint(1,100,30)

array([ 5, 46, 63, 14, 70, 17,  2,  2, 11, 31, 67, 46,  4, 55, 94, 62, 73,
       63, 81, 90, 72, 50, 68, 46, 37, 73, 86, 60, 91, 43])

In [ ]:
np.random.choice([1,3,5,7,9],size = [3,4])

array([[1, 7, 5, 5],
       [3, 5, 1, 3],
       [3, 7, 7, 9]])

In [ ]:
np.random.seed(45)
np.random.choice([2,4,6,8,0],size = [3,4])

array([[8, 8, 0, 2],
       [8, 0, 4, 2],
       [4, 4, 2, 2]])

In [ ]:
np.random.seed(45)
np.random.choice([0,1],size = [3,4])

array([[1, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 1, 0]])

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x = np.flip(arr_2d)
x

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
#MATPLOTLIB - Data visualization library based on numpy

In [ ]:
# 0,1,2
# 0,1,2,3
x[1,3]

5

In [ ]:
x[0,2]

10